
function SubtractSum(n){
    let num= [
        'kiwi',
        'pear',
        'kiwi',
        'banana',
        'melon',
        'banana',
        'melon',
        'pineapple',
        'apple',
          'pineapple',
          'cucumber',
          'pineapple',
          'cucumber',
          'orange',
          'grape',
          'orange',
          'grape',
          'apple',
          'grape',
          'cherry',
          'pear',
          'cherry',
          'pear',
          'kiwi',
          'banana',
          'kiwi',
          'apple',
          'melon',
          'banana',
          'melon',
          'pineapple',
          'melon',
          'pineapple',
          'cucumber',
          'orange',
          'apple',
          'orange',
          'grape',
          'orange',
          'grape',
          'cherry',
          'pear',
          'cherry',
          'pear',
          'apple',
          'pear',
          'kiwi',
          'banana',
          'kiwi',
          'banana',
          'melon',
          'pineapple',
          'melon',
          'apple',
          'cucumber',
          'pineapple',
          'cucumber',
          'orange',
          'cucumber',
          'orange',
          'grape',
          'cherry',
          'apple',
          'cherry',
          'pear',
          'cherry',
          'pear',
          'kiwi',
          'pear',
          'kiwi',
          'banana',
          'apple',
          'banana',
          'melon',
          'pineapple',
          'melon',
          'pineapple',
          'cucumber',
          'pineapple',
          'cucumber',
          'apple',
          'grape',
          'orange',
          'grape',
          'cherry',
          'grape',
          'cherry',
          'pear',
          'cherry',
          'apple',
          'kiwi',
          'banana',
          'kiwi',
          'banana',
          'melon',
          'banana',
          'melon',
          'pineapple',
          'apple',
          'pineapple']
    
    
    
    
    do{let b = 0
    let a = `${n}`
        for(let i = 0 ;i<a.length ; i++){
            b+=+(a[i])
        }
        n-=b
    }while(n>100)
    
    return num[n+1]
  }
  console.log(SubtractSum(10))